---
- hosts: all
  gather_facts: false
  sudo: yes

  tasks:
    - action: fireball

- hosts: rethinkdb_all_hosts
  connection: fireball
  vars_files: [ "group_vars/defaults.yml" ]
  roles:
  - role: rethinkdb_common
  handlers:
  - include: handlers/main.yml

- hosts: rethinkdb_serve_hosts
  connection: fireball
  vars_files: [ "group_vars/defaults.yml" ]
  roles:
  - role: rethinkdb_serve
  - { role: rethinkdb_sshtunnel, when: "rethinkdb_sshtunnel" }
  handlers:
  - include: handlers/main.yml

- hosts: rethinkdb_proxy_hosts
  connection: fireball
  vars_files: [ "group_vars/defaults.yml" ]
  roles:
  - role: rethinkdb_proxy
  - { role: rethinkdb_sshtunnel, when: "rethinkdb_sshtunnel" }
  handlers:
  - include: handlers/main.yml