---
- name: Get rethinkdb repo
  get_url: dest=/tmp/rethinkdb.repo  url=http://download.rethinkdb.com/centos/6/{{ ansible_machine }}/rethinkdb.repo
  when: ansible_os_family == 'RedHat'

- name: Install rethinkdb repo
  command: cp /tmp/rethinkdb.repo /etc/yum.repos.d/rethinkdb.repo

- name: Install the rethinkdb package
  yum: name=rethinkdb state=installed

- name: Create the rethinkdb user
  user: name={{ rethinkdb_user }}

- name: Create the rethinkdb group
  group: name={{ rethinkdb_group }}